### PR TITLE
Suggestion for resolving reject_bad_trials issue

### PR DESCRIPTION
**Pull request by estellerv**
I tried, it works !!
Waiting for your approval @annesodub

### CODE REVIEW

**Comment by annesodub** [comment]
@estellerv OK, could you please make your modification directly on the reject_bad_trials.m file. The principle of Git is to allow to review the modifications made on a file. By creating a new one _TEMP I have no easy way to see what part of the code you modify (I had to compare the two file to see your modifications). 

In terms of code, your modifications are OK and well commented 👍  If you double check that all indices are properly set in trial_description and that the new .set files contains the trials that should be kept, then it sound good to me!  

Before I merge, could you please remove the _TEMP file and make the modifications directly onto the reject_bad_trials.m file? 
A+
AnneSo

**Comment by estellerv** [comment]
Yes, done !
Thanks !

**Comment by annesodub** [comment]
Salut Estelle, 
j'aimerais mieux m'occuper des merges sur la branche develop (cela ne t'empêche pas d'exectuer le code qui est sur ta branche). Je n'ai pas pu vérifier tes derni;res modifications....

**Comment by estellerv** [comment]
Hello AnneSo,
Ah pardon, j'avais cru comprendre que tu avais checké le code et qu'il suffisait que j'inclue mes modifs dans le fichier reject_bad_trials et que je supprime le fichier temporaire...  J'avais mal compris, my bad !...

**Pull request merged**
